
# feature the train_set
train_result <- read.csv('train_labels.csv')
dat <- read.csv('train_values.csv')
dat <- dat[,2:14]
dat$slope_of_peak_exercise_st_segment <- as.factor(dat$slope_of_peak_exercise_st_segment)
dat$slope_1 <- dat$slope_of_peak_exercise_st_segment
dat$slope_1 <- factor(dat$slope_1,
                      levels = c(1,2,3),
                      labels = c(1,0,0))
dat$slope_2 <- dat$slope_of_peak_exercise_st_segment
dat$slope_2 <- factor(dat$slope_2,
                      levels = c(1,2,3),
                      labels = c(0,1,0))
dat$slope_3 <- dat$slope_of_peak_exercise_st_segment
dat$slope_3 <- factor(dat$slope_3,
                      levels = c(1,2,3),
                      labels = c(0,0,1))
dat$slope_of_peak_exercise_st_segment <- NULL

dat$thal <- factor(dat$thal,
                   levels = c("normal","reversible_defect","fixed_defect"),
                   labels = c(0,1,-1))
dat$thal_rever <- dat$thal
dat$thal_rever <- factor(dat$thal_rever,
                         levels = c(0,1,-1),
                         labels = c(0,1,0))
dat$thal_fixed <- dat$thal
dat$thal_fixed <- factor(dat$thal_fixed,
                         levels = c(0,1,-1),
                         labels = c(0,0,1))
dat$thal <- NULL
dat$chest_pain_type <- as.factor(dat$chest_pain_type)
dat$chestp_1 <- dat$chest_pain_type
dat$chestp_1 <- factor(dat$chestp_1,
                       levels = c(1,2,3,4),
                       labels = c(1,0,0,0))
dat$chestp_2 <- dat$chest_pain_type
dat$chestp_2 <- factor(dat$chestp_2,
                       levels = c(1,2,3,4),
                       labels = c(0,1,0,0))
dat$chestp_3 <- dat$chest_pain_type
dat$chestp_3 <- factor(dat$chestp_3,
                       levels = c(1,2,3,4),
                       labels = c(0,0,1,0))
dat$chestp_4 <- dat$chest_pain_type
dat$chestp_4 <- factor(dat$chestp_4,
                       levels = c(1,2,3,4),
                       labels = c(0,0,0,1))
dat$chest_pain_type <- NULL
dat$sex <- as.factor(dat$sex)
dat$fasting_blood_sugar_gt_120_mg_per_dl <- as.factor(dat$fasting_blood_sugar_gt_120_mg_per_dl)
dat$resting_ekg_results <- dat$resting_ekg_results
dat$num_major_vessels <- as.factor(dat$num_major_vessels)
dat$resting_ekg_results <- as.factor(dat$resting_ekg_results)
dat$exercise_induced_angina <- as.factor(dat$exercise_induced_angina)

dat$resting_blood_pressure <- scale(dat$resting_blood_pressure)
dat$serum_cholesterol_mg_per_dl <- scale(dat$serum_cholesterol_mg_per_dl)
dat$age <- scale(dat$age)
dat$max_heart_rate_achieved <- scale(dat$max_heart_rate_achieved)
dat$result <- train_result$heart_disease_present
train_set <- dat
summary(train_set)
rm(train_result)
rm(dat)


#feature the test_set
dat <- read.csv('test_values.csv')
dat <- dat[,2:14]
dat$slope_of_peak_exercise_st_segment <- as.factor(dat$slope_of_peak_exercise_st_segment)
dat$slope_1 <- dat$slope_of_peak_exercise_st_segment
dat$slope_1 <- factor(dat$slope_1,
                      levels = c(1,2,3),
                      labels = c(1,0,0))
dat$slope_2 <- dat$slope_of_peak_exercise_st_segment
dat$slope_2 <- factor(dat$slope_2,
                      levels = c(1,2,3),
                      labels = c(0,1,0))
dat$slope_3 <- dat$slope_of_peak_exercise_st_segment
dat$slope_3 <- factor(dat$slope_3,
                      levels = c(1,2,3),
                      labels = c(0,0,1))
dat$slope_of_peak_exercise_st_segment <- NULL

dat$thal <- factor(dat$thal,
                   levels = c("normal","reversible_defect","fixed_defect"),
                   labels = c(0,1,-1))
dat$thal_rever <- dat$thal
dat$thal_rever <- factor(dat$thal_rever,
                         levels = c(0,1,-1),
                         labels = c(0,1,0))
dat$thal_fixed <- dat$thal
dat$thal_fixed <- factor(dat$thal_fixed,
                         levels = c(0,1,-1),
                         labels = c(0,0,1))
dat$thal <- NULL
dat$chest_pain_type <- as.factor(dat$chest_pain_type)
dat$chestp_1 <- dat$chest_pain_type
dat$chestp_1 <- factor(dat$chestp_1,
                       levels = c(1,2,3,4),
                       labels = c(1,0,0,0))
dat$chestp_2 <- dat$chest_pain_type
dat$chestp_2 <- factor(dat$chestp_2,
                       levels = c(1,2,3,4),
                       labels = c(0,1,0,0))
dat$chestp_3 <- dat$chest_pain_type
dat$chestp_3 <- factor(dat$chestp_3,
                       levels = c(1,2,3,4),
                       labels = c(0,0,1,0))
dat$chestp_4 <- dat$chest_pain_type
dat$chestp_4 <- factor(dat$chestp_4,
                       levels = c(1,2,3,4),
                       labels = c(0,0,0,1))
dat$chest_pain_type <- NULL
dat$sex <- as.factor(dat$sex)
dat$fasting_blood_sugar_gt_120_mg_per_dl <- as.factor(dat$fasting_blood_sugar_gt_120_mg_per_dl)
dat$resting_ekg_results <- dat$resting_ekg_results
dat$num_major_vessels <- as.factor(dat$num_major_vessels)
dat$resting_ekg_results <- as.factor(dat$resting_ekg_results)
dat$exercise_induced_angina <- as.factor(dat$exercise_induced_angina)

dat$resting_blood_pressure <- scale(dat$resting_blood_pressure)
dat$serum_cholesterol_mg_per_dl <- scale(dat$serum_cholesterol_mg_per_dl)
dat$age <- scale(dat$age)
dat$max_heart_rate_achieved <- scale(dat$max_heart_rate_achieved)
test_set <- dat
rm(dat)
